// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuleRegistrationSiarad.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ModuleRegistrationSiarad.Migrations
{
    [DbContext(typeof(ModuleRegistrationContext))]
    [Migration("20191121134035_ModuleRegistrationDatabase_v1")]
    partial class ModuleRegistrationDatabase_v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.Module", b =>
                {
                    b.Property<string>("year");

                    b.Property<string>("module_id");

                    b.Property<string>("coordinator_id")
                        .IsRequired();

                    b.Property<string>("module_title")
                        .IsRequired();

                    b.HasKey("year", "module_id");

                    b.ToTable("module");
                });

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.Staff", b =>
                {
                    b.Property<int>("auto_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("module_id")
                        .IsRequired();

                    b.Property<string>("staff_id")
                        .IsRequired();

                    b.HasKey("auto_id");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.Student", b =>
                {
                    b.Property<string>("user_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("forename")
                        .IsRequired();

                    b.Property<string>("surname")
                        .IsRequired();

                    b.HasKey("user_id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.StudentsRegistreredForSpecificModules", b =>
                {
                    b.Property<int>("auto_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("module_id");

                    b.Property<string>("user_id");

                    b.HasKey("auto_id");

                    b.ToTable("registered_students");
                });
#pragma warning restore 612, 618
        }
    }
}
