// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuleRegistrationSiarad.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ModuleRegistrationSiarad.Migrations
{
    [DbContext(typeof(ModuleRegistrationContext))]
    [Migration("20191113151820_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.Module", b =>
                {
                    b.Property<string>("ModuleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ModuleTitle");

                    b.Property<string>("StaffId")
                        .IsRequired();

                    b.HasKey("ModuleId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.Staff", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ModuleId");

                    b.Property<string>("StaffId");

                    b.HasKey("AutoId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.Student", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Forename");

                    b.Property<string>("Surname");

                    b.HasKey("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ModuleRegistrationSiarad.Models.StudentsRegistreredForSpecificModules", b =>
                {
                    b.Property<int>("AutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ModuleId");

                    b.Property<string>("UserId");

                    b.HasKey("AutoId");

                    b.ToTable("RegisteredStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
